name: GameBot Discord

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  reset-and-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - name: Reset disponibilités + poster question
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          QUESTION_CHANNEL_ID: ${{ secrets.QUESTION_CHANNEL_ID }}
          RESULTS_CHANNEL_ID: ${{ secrets.RESULTS_CHANNEL_ID }}
        run: node daily.js # <--- Ici, on lance bien daily.js
